### ISSUE TITLE
datapackage.json - Failed

### ISSUE THREAD

**Issue by tobiasschellhorn** [openspending/openspending#1452]
fiscal.helpers.save_primarykey
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_fiscal/processors/helpers/save_primarykey.py", line 9, in <module>
    process(modify_datapackage=modify_datapackage)
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 223, in process
    ctx.datapackage = modify_datapackage(ctx.datapackage, ctx.parameters, ctx.stats)
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_fiscal/processors/helpers/save_primarykey.py", line 5, in modify_datapackage
    dp['savedPk'] = dp['resources'][0]['schema']['primaryKey']
KeyError: 'primaryKey'

**Comment by tlacoyodefrijol** [comment]
@tobiasschellhorn Could you give us more context? Is this an error from the Packager?

**Comment by annafralberts** [comment]
I had the exact same error while trying to upload dummy files, I eventually only try to model the most basic fields and one hierarchy and even that didn't work. 
Yes, it's an error from the packager

**Comment by michaeljokf** [comment]
I have been experiencing the same errors! This seems to be the case with any dataset. Will this be fixed?

**Comment by michaeljokf** [comment]
This seems to happen with any dataset. I have done it multiple times (with attached dataset) and checked the mapping as well. Upload just does not go through... 
[rheinland-pfalz-19-20.zip](https://github.com/openspending/openspending/files/3368688/rheinland-pfalz-19-20.zip)

**Comment by michaeljokf** [comment]
this is what it says in my OS account:  Failed to load data from https://openspending.org/package/status?datapackage=https%3A%2F%2Fdatastore.openspending.org%2Fa6a16b964a7e784f99adecc47f26318a%2Frheinland-pfalz-19-20%2Fdatapackage.json

**Comment by michaeljokf** [comment]
is there any updates on this? I still get the same error message and I do not know how I am supposed to upload data anymore. This is a problem, because it is for an ongoing project with the German Federal State of Rheinland-Pfalz. Any ideas? 

![Bildschirmfoto von »2019-08-08 14-10-26«](https://user-images.githubusercontent.com/22743376/62702199-6505b400-b9e6-11e9-8cfa-443910c5bef3.png)

**Comment by michaeljokf** [comment]
Ok looks like I got it to publish now: https://openspending.org/viewer/a6a16b964a7e784f99adecc47f26318a:rp1920 
not sure if everything is correctly displayed yet. 
It seems like you guys have changed the instructions for mapping (there are no partial/complete identifiers on lower levels anymore...

The reason I think it worked this time: I took the text columns and mapped those as unique identifiers and completely left out the corresponding identifiers. Earlier I was always mapping the IDs as "unique identifiers" and the string with text as "display label"

**Comment by michaeljokf** [comment]
issue has been fixed. Was not the mapping after all, someone must have fixed it but did not post about this here :-)

**Comment by tobiasschellhorn** [comment]
i still get the error:

fiscal.helpers.save_primarykey
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_fiscal/processors/helpers/save_primarykey.py", line 9, in <module>
    process(modify_datapackage=modify_datapackage)
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 223, in process
    ctx.datapackage = modify_datapackage(ctx.datapackage, ctx.parameters, ctx.stats)
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_fiscal/processors/helpers/save_primarykey.py", line 5, in modify_datapackage
    dp['savedPk'] = dp['resources'][0]['schema']['primaryKey']
KeyError: 'primaryKey

![image](https://user-images.githubusercontent.com/3539618/64348854-3505fc80-cff6-11e9-9ef5-5f9ff430cc86.png)
