### ISSUE TITLE
Years mixed up on the x axis

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#855]
Happens when selecting "Group by years" in the viewer

- Years in a inverse chronological order
- Years mixed up in the axis

<img width="594" alt="capture d ecran 2016-02-11 a 00 06 36" src="https://cloud.githubusercontent.com/assets/6681719/12972693/40197a7a-d09f-11e5-85f8-1c021ad91b38.png">
<img width="812" alt="capture d ecran 2016-02-11 a 00 15 50" src="https://cloud.githubusercontent.com/assets/6681719/12972696/4659577a-d09f-11e5-986d-3a3b53b3e92b.png">

**Comment by cecilaki** [comment]
@akariv can we move this in the high priority pile?

**Comment by akariv** [comment]
No problem

**Comment by borysyuk** [comment]
@akariv (cc @pwalsh, @cecilaki ) It happens  because we sort data by selected dimension and take first x records (x depends on chart type)

**Comment by akariv** [comment]
@borysyuk from what I see in the API, the data is requested to be sorted by the amount (desc) and not by the selected dimension. Is there an extra step of re-sorting the results?

**Comment by borysyuk** [comment]
@akariv  I am sorry, measure not dimension

**Comment by akariv** [comment]
Okay, so looking further into this:
- Sorting by `amount.desc` actually makes sense for other charts (e.g. pie chart, tree-map). 
- Even for bar charts and line charts it sometimes makes sense to sort by amount (e.g. distribution of expenses by region)
- In the original website, pudo solved this by allowing to sort on any dimension/measure (see for example http://spendb-dev.herokuapp.com/datasets/wb-contract-awards?view=linechart)

so I think we should probably solve this by giving the user the option to sort by anything rather than selecting arbitrarily a 'best thing to sort by' for each chart.

On a side note, there's also a 'category' selection in the original website which I think we're not implementing right now (and probably should).

@cecilaki @pwalsh @borysyuk

**Comment by cecilaki** [comment]
Ok, but what happens when we sort by `groups=date`?

**Comment by akariv** [comment]
Fixed, deploying now

**Comment by cecilaki** [comment]
Looks like something broke:

Still happening in Bar Charts 

<img width="676" alt="capture d ecran 2016-04-26 a 07 23 38" src="https://cloud.githubusercontent.com/assets/6681719/14808778/14ebd282-0b80-11e6-9d30-3ad04345ad00.png">

And Line Charts
<img width="678" alt="capture d ecran 2016-04-26 a 07 24 43" src="https://cloud.githubusercontent.com/assets/6681719/14808783/23a3e9f4-0b80-11e6-8299-fde07ef24fa0.png">

**Comment by akariv** [comment]
Bar charts are always ordered by the amount, not the x-axis (you can change that if you want using the sorting controls). 
As for line charts, see https://github.com/openspending/openspending/issues/917

**Comment by cecilaki** [comment]
Oh ok --> Improvement for user guidance then by indicating it's possible.

I understand the need for flexibility in allowing sorting in different ways, with different dimensions on the X-axis, and not only by years or time, especially if the dataset doesn't allow it. 

Would that make sense to make rule that would order the x-axis by years (or months.. anytime time period of the dataset) if `datetime`is selected in the x-axis, and not by amount?

Does that make sense for a user to sort a bar chart by amount and have reverse years in the X-axis?  
What do you think @smth ? 

And about the Line Charts, I've observed they can actually work sorted by time **if/when** you did the manipulation on the Bar Chart, removed the viz and start a new line chart over again. ( _So if we fix that for the Line charts, as a default behavior, then it's also possible to lock it for the Bar Charts I guess?_ )

Steps to reproduce the working line charts:
1 - Open a Bar Chart viz type
2 - Sort by years
3 - Delete and remove the Bar Chart
4 - Create a Line Chart
5 - Ta-dah : 

<img width="676" alt="capture d ecran 2016-04-26 a 08 19 43" src="https://cloud.githubusercontent.com/assets/6681719/14810196/87ad5b66-0b89-11e6-96be-c1dc0ede4a4f.png">

**Comment by akariv** [comment]
Yes, the viewer 'remembers' the selected sorting and applies it to the line chart - which is also a bug, as the line chart should always be sorted by the x-axis.

It's possible to make the default sorting for *bar charts* to be by the x-axis if it's a date/time, and otherwise to be by the measure descending (as it's today) - let's open a separate issue for that enhancement.
