### ISSUE TITLE
Clear sorting, grouping and filters when changing state

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#971]
Right now these remain, which might cause invalid API requests to be sent.
We need to clear these when all visualisations are cleared from the workspace.

**Comment by cecilaki** [comment]
Plus visually speaking, this is what happens currently when a user closes a visualisation in the workspace: 
Need to be cleared.

<img width="858" alt="capture d ecran 2016-05-16 a 16 10 50" src="https://cloud.githubusercontent.com/assets/6681719/15292070/8c614d04-1b81-11e6-9e53-b4ed88827a48.png">

**Comment by kravets-levko** [comment]
@akariv  Seems that I've fixed something like this during my work on #972. Please re-check this bug and LMK if I should analyze it deeper. Thanks!

**Comment by akariv** [comment]
OK, I'll wait for the PR and I'll try to reproduce.

**Comment by akariv** [comment]
Still reproduces:
- Go to http://next.openspending.org/viewer
- Selected dataset is 'Kisela Voda'. Default ordering is 'yznos.sum:desc`
- Choose 'Moldova 2005-2014 from the selection'
- Ordering remains 'yznos.sum:desc`

**Comment by akariv** [comment]
Also, seems that displayed filters are not cleared from screen (though it seems they are not in effect):
